### ISSUE TITLE
Unable to download one or more archives

### ISSUE THREAD

**Issue by SpartanM23** [azraerl/serenity#14]
So i wanted to download the modlist but it keep failing at the end.

I attached the log for more clarity but i think it's a problem with Mod Organizer

[Wabbajack.current.log](https://github.com/azraerl/serenity/files/7503200/Wabbajack.current.log)

**Comment by azraerl** [comment]
Please follow #13 for enbseries file.

As for the other two files, you can grab them from [mirror](https://mega.nz/folder/qcd3wC5L#dsiyuJdQMk0DJvpzcA7q4w), or `Use Network Workaround (slow)` in Wabbajack options - along with reducing `Download Threads` to 1.

**Comment by SpartanM23** [comment]
Thanks it worked! Just didn't need to grab the other file from mirror. :D

**Comment by azraerl** [comment]
👍🏽
