### ISSUE TITLE
Can't extract skse_loader into Stock Game

### ISSUE THREAD

**Issue by SpartanM23** [azraerl/serenity#15]
Okay so i know i already post for a problem today but here again i don't know how to solve this even after searching for it. During the installation and the extraction of the mods, it keeps failling with the extraction of skse_loader because it don't have the permission to do it. 
I'm connected as administrator and i even run wabbajack as administrator. If i move the file with another name into the folder there's no problem (i just can't name it skse_loader) but because the installation failed, Mod Organizer is not ready to launch. 
Is there a way to grant permission to extract skse_loader? 
I join the log this time t
[Wabbajack.current.log](https://github.com/azraerl/serenity/files/7505180/Wabbajack.current.log)
oo

**Comment by azraerl** [comment]
This is an antivirus interference. Please disable it to proceed with install.
See below common information about the case:

### Antivirus Interference

If you are experiencing problems running Wabbajack such as the exe being deleted or no progress during the installation phase, try adding the folder where your Wabbajack executable is and the folder where you wish to install the modlist to exclusions in your antivirus of choice.

Find out how to via: https://lmgtfy.app/?q=how+to+add+exclusions+to+antivirus

Note: If you're using Webroot or any other free 3rd party antivirus it's likely that adding the folders to exclusions will not be enough and you'll need to disable or uninstall your 3rd party AV as they can incorrectly mark usvfs_proxy_x86.exe, among other files, as a virus, a file needed for Mod Organizer 2 to work. We recommend doing so anyway in case it's a free one, as Windows Defender is likely much better at stopping threats than that is (according to data from av-test.org https://www.av-test.org/en/antivirus/home-windows/).

If you still think a file is a virus, you can upload it to virustotal and get it scanned by multiple antiviruses. Here is a scan of the file mentioned above, of which 2 antiviruses report a false positive:
https://www.virustotal.com/gui/file/356c029b7bf0bed41460ceacf2c756560101b9b0977c349925d81d76392dd0c4/detection

**Comment by SpartanM23** [comment]
Thanks again for your help! Everything works now, i even managed to launch the game ^^
I can't wait to test the modpack!

**Comment by azraerl** [comment]
👍🏽 
It is modlist, though. Also you may join dedicated Serenity discord - [Emporio's Emporium](https://discord.gg/haVcdTvCce) - for discussion and stuff.
