### ISSUE TITLE
Solution for `Unable to download xLODGen.83.7z`

### ISSUE THREAD

**Issue by dicemanproductionz** [azraerl/serenity#16]
**Describe the bug**
Currently unable to download the following file which causes the installation to fail in wabbajack (MegaDownloader+State|https://mega.nz/file/EcJhgKpY#4Q86Rd1hUepjm233r8Q_7x3fTWx9axJN2CUc8FXrBsg)

**To Reproduce**
Run the installation of the modlist through Wabbajack

**Comment by azraerl** [comment]
xLODGen v0.83 has been taken down by xEdit team, however it has open permissions.
So, here is the [mirror for xLODGen v0.83](https://mega.nz/folder/qcd3wC5L#dsiyuJdQMk0DJvpzcA7q4w)

> 1. Open folder which you've picked as Serenity downloads in Wabbajack
> 2. Download [xLODGen v0.83 from the mirror](https://mega.nz/folder/qcd3wC5L#dsiyuJdQMk0DJvpzcA7q4w)
> 3. Place it into that folder and run Wabbajack install once again
> 
> Also you may join dedicated Serenity discord - [Emporio's Emporium](https://discord.gg/haVcdTvCce)

P.S.: I will leave this one open to avoid further creation of duplicated issues.
