### ISSUE TITLE
Solved - Wabbajack download failing

### ISSUE THREAD

**Issue by ElixirMusic** [azraerl/serenity#20]
Hey guys :)

This is my first time trying to download a modpack using wabbajack so sorry for being noob level 1000!

I've followed the instructions very carefully but it keeps failing. It will fail on (9/22) hastag remaining archives 983 of 983. I've posted the log text below. The first few lines of text say about increasing my page file size, I've done this and reset my pc, checked that it is set at 20000 MB and it is, so I'm not sure why it's still saying my page file size is 4.8 GB. I've also downgraded my Skyrim to 1.53.97 and used my documents folder as the steam skyrim download location. Thanks in advance :) :

0.23 - Wabbajack Build - f9f0ecdd80ef88be26f63b7ece801f0f3deb0961
0.23 - Running in C:\Wabbajack
0.31 - Detected Windows Version: 10.0.19043.0
0.31 - System settings - (31.9GB RAM) (4.8GB Page), Display: 1920 x 1080 (7.9GB VRAM - VideoMemorySizeMb=10240)
0.31 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.32 - Outside of standard install folder, not updating
0.45 - Steam: Found no Regex matches in Steam Config at c:/users/andy/documents/steam\config\config.vdf
0.45 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Users\Andy\Documents\Steam\steamapps\common\Steamworks Shared"
0.45 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "C:\Users\Andy\Documents\Steam\steamapps\common\Skyrim Special Edition"
0.45 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/users/andy/documents/steam\steamapps\common\Steamworks Shared"
0.45 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "c:/users/andy/documents/steam\steamapps\common\Skyrim Special Edition"
0.45 - GOG: GOG was not found in the registry
0.45 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.45 - EGS: ModSdkMetadataDir from Registry does not exist at C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests
0.46 - Origin: InstallPath for Origin.OFR.50.0002148 does not exist at C:\Program Files (x86)\Origin Games\STAR WARS Battlefront II\
0.73 - Wabbajack Version: 2.5.3.5
1.05 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\EA Games\Battlefield V for Game Origin.OFR.50.0002683
1.05 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\EA Games\Battlefield V for Game Origin.OFR.50.0002683
1.05 - Origin: Game Origin.OFR.50.0002683 was found using the Api but has no Path
1.11 - Build server is alive
1.11 - Build server is alive
1.12 - File hash check (-42) b7540a26be8c712fee847de470333e08986c069d75d58419f952f5b2e22ec794
1.12 - File hash check (-42) b7540a26be8c712fee847de470333e08986c069d75d58419f952f5b2e22ec794
1.23 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\PopCap Games\Peggle for Game Origin.OFR.50.0000461
1.23 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\PopCap Games\Peggle for Game Origin.OFR.50.0000461
1.23 - Origin: Game Origin.OFR.50.0000461 was found using the Api but has no Path
1.4 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\PopCap Games\Peggle Nights for Game OFB-EAST:58738
1.4 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\PopCap Games\Peggle Nights for Game OFB-EAST:58738
1.4 - Origin: Game OFB-EAST:58738 was found using the Api but has no Path
1.62 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\EA Games\STAR WARS Battlefront II for Game Origin.OFR.50.0002148
1.62 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\EA Games\STAR WARS Battlefront II for Game Origin.OFR.50.0002148
1.62 - Origin: Game Origin.OFR.50.0002148 was found using the Api but has no Path
1.62 - Origin: Found game Battlefield 1 Standard Edition - PC - RoW (Origin/3PDD) (Origin.OFR.50.0000557) at "C:\Program Files\EA Games\Battlefield 1"
1.62 - Origin: Found game Battlefield V Standard Edition - PC - ROW (Origin) (Origin.OFR.50.0002683) at ""
1.62 - Origin: Found game FIFA 21 Standard Edition Launch - PC - ROW (Origin.OFR.50.0003912) at "C:\Program Files\EA Games\FIFA 21"
1.62 - Origin: Found game Peggle Standard Edition - Mac/PC - WW (Origin.com) (Origin.OFR.50.0000461) at ""
1.62 - Origin: Found game Peggle Nights - Mac/PC   - WW (Origin.com) (OFB-EAST:58738) at ""
1.62 - Origin: Found game Star Wars Battlefront II: Standard Edition - PC - NA & LATAM (Origin) (Origin.OFR.50.0002148) at ""
5.69 - Loading ModLists from GitHub
6.16 - Error downloading modlist image OME(FT)
6.17 - Error downloading modlist image OME(FT)
50.82 - Starting to install Serenity2
50.83 - Cleaning VFS, this may take a bit of time
50.86 - Starting Installer Task
50.86 - Installation has Started
50.86 - File hash check (-42) b7540a26be8c712fee847de470333e08986c069d75d58419f952f5b2e22ec794
51.23 - Configuring Processor
51.24 - Install Folder: C:\Modlists\Serenity
51.24 - Downloads Folder: C:\Modlists\Serenity\downloads
51.24 - Game Folder: C:\Users\Andy\Documents\Steam\steamapps\common\Skyrim Special Edition
51.24 - Wabbajack Folder: C:\Wabbajack
51.24 - Drive watcher is starting. Will warn at 8GB and error at 4GB
51.24 - Starting Drive watcher on C:\ currently 149GB free out of 837.8GB
51.24 - Validating Game ESMs
51.25 - Creating Output Folders
51.36 - Optimizing ModList
51.36 - Optimizing ModList directives
53.13 - Looking for files to delete
53.22 - Cleaning empty folders
53.79 - Looking for unmodified files
54.13 - Updating ModList
54.13 - Optimized 179031 directives to 179031 required
54.16 - Hashing Archives
54.16 - Looking for files to hash
54.47 - Found 1040 total files, 983 matching filesize
54.72 - Downloading Missing Archives
54.72 - Missing 20 archives
54.72 - Getting Nexus API Key, if a browser appears, please accept
54.73 - Loading server whitelist
54.91 - Loaded permissions for 649 servers and 284 Google Drive files
54.91 - File hash check (-42) b7540a26be8c712fee847de470333e08986c069d75d58419f952f5b2e22ec794
54.95 - Downloading Data_Skyrim - Interface.bsa
54.95 - Downloading Data_Skyrim - Shaders.bsa
54.95 - Downloading Data_Skyrim - Sounds.bsa
54.95 - Downloading Data_Skyrim - Misc.bsa
54.95 - Downloading Data_Skyrim - Textures3.bsa
54.95 - Downloading Data_Skyrim - Textures0.bsa
54.95 - Downloading Data_Skyrim - Textures5.bsa
54.95 - Downloading Data_ccBGSSSE001-Fish.bsa
54.95 - (Retry 1 of 5), got exception (2) The system cannot find the file specified: [C:\Users\Andy\Documents\Steam\steamapps\common\Skyrim Special Edition\Data\ccBGSSSE001-Fish.bsa], waiting 100ms
55.05 - (Retry 2 of 5), got exception (2) The system cannot find the file specified: [C:\Users\Andy\Documents\Steam\steamapps\common\Skyrim Special Edition\Data\ccBGSSSE001-Fish.bsa], waiting 200ms
55.26 - (Retry 3 of 5), got exception (2) The system cannot find the file specified: [C:\Users\Andy\Documents\Steam\steamapps\common\Skyrim Special Edition\Data\ccBGSSSE001-Fish.bsa], waiting 400ms
55.67 - (Retry 4 of 5), got exception (2) The system cannot find the file specified: [C:\Users\Andy\Documents\Steam\steamapps\common\Skyrim Special Edition\Data\ccBGSSSE001-Fish.bsa], waiting 800ms
55.77 - Hashed download is incorrect
55.77 - Loading for alternative to l/34Syb1rXg=
55.78 - Hashed download is incorrect
55.78 - Loading for alternative to SwnAPr6pbzg=
55.92 - No alternative for SwnAPr6pbzg= could be found
55.92 - No alternative for l/34Syb1rXg= could be found
55.92 - Downloading Data_Skyrim - Meshes0.bsa
55.92 - Downloading Data_Skyrim - Animations.bsa
56.48 - (Retry 5 of 5), got exception (2) The system cannot find the file specified: [C:\Users\Andy\Documents\Steam\steamapps\common\Skyrim Special Edition\Data\ccBGSSSE001-Fish.bsa], waiting 1600ms
57.24 - Hashed download is incorrect
57.24 - Loading for alternative to 5xD6UEtvt3M=
57.29 - No alternative for 5xD6UEtvt3M= could be found
57.29 - Downloading Data_Skyrim - Meshes1.bsa
57.33 - Hashed download is incorrect
57.33 - Loading for alternative to 7ZEj5ntJZIc=
57.35 - No alternative for 7ZEj5ntJZIc= could be found
57.35 - Downloading Data_Skyrim - Textures2.bsa
58.09 - Loading for alternative to TxUe36eG4W0=
58.13 - No alternative for TxUe36eG4W0= could be found
58.13 - Downloading Data_Skyrim - Textures8.bsa
58.42 - Hashed download is incorrect
58.42 - Loading for alternative to WJzdWWq7n8M=
58.47 - No alternative for WJzdWWq7n8M= could be found
58.47 - Downloading Data_Skyrim.esm
61.39 - Hashed download is incorrect
61.39 - Loading for alternative to gGA1UynjlR8=
61.44 - No alternative for gGA1UynjlR8= could be found
61.44 - Downloading Data_Update.esm
62.66 - Hashed download is incorrect
62.66 - Loading for alternative to VX7KHQ0qSXM=
62.7 - No alternative for VX7KHQ0qSXM= could be found
62.7 - Downloading Data_HearthFires.esm
62.79 - Hashed download is incorrect
62.79 - Loading for alternative to XlKELPX7jog=
62.84 - No alternative for XlKELPX7jog= could be found
62.84 - Downloading Data_Dragonborn.esm
62.91 - Hashed download is incorrect
62.91 - Loading for alternative to w7YJ2li+67E=
62.92 - No alternative for w7YJ2li+67E= could be found
62.92 - Downloading Data_Dawnguard.esm
63.27 - Hashed download is incorrect
63.27 - Loading for alternative to v593yGFgPDo=
63.31 - No alternative for v593yGFgPDo= could be found
63.32 - Downloading SkyrimSE.exe
63.66 - Hashed download is incorrect
63.66 - Loading for alternative to F76LaGyCAJA=
63.71 - No alternative for F76LaGyCAJA= could be found
63.71 - Downloading Skyrim.ccc
63.71 - Hashed download is incorrect
63.71 - Loading for alternative to Wsq6jhOx4YM=
63.71 - Hashed download is incorrect
63.71 - Loading for alternative to L2b/YNPnYDg=
63.74 - No alternative for Wsq6jhOx4YM= could be found
63.76 - No alternative for L2b/YNPnYDg= could be found
65.14 - Hashed download is incorrect
65.14 - Loading for alternative to oct60LUJHOc=
65.17 - No alternative for oct60LUJHOc= could be found
65.79 - Hashed download is incorrect
65.79 - Loading for alternative to TvzBPkbzJjI=
65.83 - No alternative for TvzBPkbzJjI= could be found
73.34 - Hashed download is incorrect
73.34 - Loading for alternative to oIYZPu4jH2g=
73.38 - No alternative for oIYZPu4jH2g= could be found
74.41 - Hashed download is incorrect
74.41 - Loading for alternative to miIWAsh+4As=
74.46 - No alternative for miIWAsh+4As= could be found
76.1 - Hashed download is incorrect
76.1 - Loading for alternative to 6ILjbi2XOOA=
76.13 - Hashed download is incorrect
76.13 - Loading for alternative to uutAUjvgpvg=
76.14 - No alternative for 6ILjbi2XOOA= could be found
76.17 - No alternative for uutAUjvgpvg= could be found
76.2 - Hashing Remaining Archives
76.2 - Looking for files to hash
76.71 - Found 1040 total files, 983 matching filesize
76.92 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|skyrim.ccc)
76.92 - Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|skyrimse.exe)
76.92 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\dawnguard.esm)
76.92 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\dragonborn.esm)
76.92 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\hearthfires.esm)
76.92 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\update.esm)
76.92 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim.esm)
76.92 - Unable to download Data_Skyrim - Textures8.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - textures8.bsa)
76.92 - Unable to download Data_Skyrim - Textures2.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - textures2.bsa)
76.92 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - meshes1.bsa)
76.92 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - meshes0.bsa)
76.92 - Unable to download Data_Skyrim - Animations.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - animations.bsa)
76.92 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - sounds.bsa)
76.92 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - interface.bsa)
76.92 - Unable to download Data_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - textures3.bsa)
76.92 - Unable to download Data_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - textures0.bsa)
76.92 - Unable to download Data_ccBGSSSE001-Fish.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse001-fish.bsa)
76.92 - Unable to download Data_Skyrim - Textures5.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - textures5.bsa)
76.92 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - misc.bsa)
76.92 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - shaders.bsa)
76.92 - Cannot continue, was unable to download one or more archives
76.92 - File hash check (-42) b7540a26be8c712fee847de470333e08986c069d75d58419f952f5b2e22ec794
76.95 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
77.27 - File hash check (-42) b7540a26be8c712fee847de470333e08986c069d75d58419f952f5b2e22ec794

**Comment by azraerl** [comment]
Hi there,

Today I have uploaded a refreshed mod list version (1.6.3), which now require fresh Skyrim Anniversary Edition (1.6.353.0). While readme update is still in progress - sorry for that.

Either way, only thing you have to do is verify Skyrim files via Steam.

Cheers

**Comment by ElixirMusic** [comment]
That's no worries and awesome, cheers for the help!

I'll see how I get on :)

Does the steam directory location matter? Lots of mod sites say about keeping it out of the c\program files folder but that isn't mentioned

**Comment by azraerl** [comment]
Serenity uses Stock Game feature - e.g. modlist creates own copy of original game files in own directory. Thus Program Files issue should not occur, although it still may cause troubles with MO2 uvfs in some edge cases.

**Comment by ElixirMusic** [comment]
Okay cool, that makes sense. I'm already past the point I was stuck at before so we're looking good! I wish I hadn't plunged so many hours into badly modding Skyrim myself when I could just get someone who knows what they're doing to create a great game haha

**Comment by ElixirMusic** [comment]
I'm gonna have to warn you of noob alert again lol

Everything is downloaded and the game looks immense! It is opening windowed though and I've changed the settings using beth.ini to make it windowless and boarderless but it hasn't changed anything?

**Comment by ElixirMusic** [comment]
The skyrimprefs.ini file also has a bBorderless=1 and bFull Screen=1

**Comment by azraerl** [comment]
See `Serenity/mods/SSE Display Tweaks` mod and it's ini file - most of stuff is being controlled over there. Configuration file has really good comments about everything. Also you may refer to https://www.nexusmods.com/skyrimspecialedition/mods/34705
