### ISSUE TITLE
Freezing around Rorikstead settlement.

### ISSUE THREAD

**Issue by GammaHavoc** [azraerl/serenity#21]
My game seems to freeze (not crash) whenever I get within a certain distance to the Rorikstead settlement. I'm heading there for a missive quest and just after passing Gjukar's monument on the road the game freezes up. I've tried circumventing the area and approaching from a different direction but the same freeze occurs. Screen freezes, audio still plays, game becomes unresponsive.

**Comment by jconnolly-bond** [comment]
Would just like to add that am I experiencing the exact same problem.

**Comment by azraerl** [comment]
Hey there, It seems 1.6.3 got some borked file upon update - I'm looking for a solution 👍🏽

**Comment by azraerl** [comment]
> going up north of Winterhold to the sea (sky temple ruins)

From #22

> Forsworn related locations

From https://github.com/ixanza/tranquility/issues/7 as it is directly related.

Those are also affected. Issue has been narrowed down to how Wabbajack handles Stock Game files. Solution is being discussed.
Sadly fix is not directly applicable, as you need Skyrim-1.5.97 BSA files to overwrite for a hotfix

**Comment by azraerl** [comment]
A quick update on the topic: Halgari is now testing a Wabbajack update which will fix above issue.

**Comment by GammaHavoc** [comment]
Excellent! Thanks for following up!

**Comment by azraerl** [comment]
Today's release - v1.6.3.1 rebuild with fresh Wabba - should have this issue fixed.
