### ISSUE TITLE
Game Freezes ( Winterhold )

### ISSUE THREAD

**Issue by SenseiFx** [azraerl/serenity#22]
If going up north of Winterhold to the sea (sky temple ruins) there's a freeze so I need to force quit the game 

Rorikstead is the same problem, 

There might be other place's I'll keep you updated if I found new freeze area 

Specs : 
r9 3900x
32gb 3600mhz cl14
1080ti

**Comment by azraerl** [comment]
Hey there, yep - this is a known one.
https://github.com/azraerl/serenity/issues/21 - refer to this for updates.
