### ISSUE TITLE
No Paper Map No Map Markers

### ISSUE THREAD

**Issue by ReikiJake** [azraerl/serenity#4]
Map is only showing the original and not the paper map. It also has no map markers or location indicator.

I loaded into the "camping in the woods selection first then realized there was no paper map or markers.

I re-installed after deleting wabbajack hash info.
Loaded into same cell and didn't work no paper map no markers.

I deleted skyrim and all files then restored skyrim and re-installed serenity.
Loaded into same cell and did not work no paper map no markers.

I deleted serenity folder and all papermap files then redownloaded them and cleaned skyrim then re-installed serenity, I decided to load into winterhold as a mage.
Paper map worked so I played for a few hours walking around winterhold and then taking a cariage to whitrun and walking around there.
Then papermap and map markers stopped working but it was the first time I checked since the initial check after loading into winterhold.

Loaded previous save where it worked and it did not work this time.

Deleted all save data and loaded into winterhold and it did not work again.

Tried a bunch of stuff like removing a few mods I had
Dark souls bonfire menu its master and its patches for campfire and wymstooth and experimenting to see if it may have been a problem since it "may" add a map marker to winterhold.
Also tried disabling paper map and it gave me a better resolution regular map but no map markers.
Nothing worked

Scrubbed everything again and re-installed everything after updating modlist file to 1.6.0 from 1.5.3.1 and originally 1.5.3
No extra mods, no custom patches
Loaded into winterhold
Map still not working and not sure what happened to get it to work for the brief moment it did.

I play with a controller but after the first time I re-installed I loaded in with the mouse and keyboard each time. Or deleted and tried again without controller. Not sure.
Been at this for days and now am sad I cannot play the only requiem modlist available.

You have built an amazing set of mods and I love style and view of it all. I hope this gets fixed so I can play it soon. Sad I cannot continue. Not sure if I will play skyrim for a while Tinvaak has way to many features/spells and it is not requiem.

I was so happy this came back.

i7-7700hq 7th gen, gtx 1070 8gb non mobile version in a laptop, 32gb ram, on a 2tb ssd.

**Comment by ReikiJake** [comment]
I got it working by moving paper map esp to the bottom of my load order. I added my mods back and it did it again. One of them may have included a map marker but it definitely included worldspace edits. Anyhow hope this helps anyone with this problem as well as the dev to fix the issue. I also disabled the whole mod "dynamic snow on maps" but that alone did not fix it. not sure why it was still there but I def get it. Over 900 mods.

Thank you for the great modlist and all your work to keep it on here. By far one of the best. Glad this one is back it is my favorite of the Requiem ones. Hope to see it up again soon so others can enjoy it. 

Time to go Drauger hunting. Cheers

**Comment by azraerl** [comment]
Alright, glad it worked out - and sorry for the late answer here.

Only thing which perplexes me is that 1.6.0 is not even out now - I'm just going to upload it. Which includes *a lot* of bug fixes, including few for the paper world map... let's see if I've fixed this issue once and for good, as for weird reason only small % of users struggle with it (and so it's not reproducible on my pc)

**Comment by ReikiJake** [comment]
I'll download it and check it out and see if it happens with a clean start. I was using the serenity profile if that helps. 
Looking forward to the new changes for spellblades and the addition of the headhunter mod. I kinda wish it had skyrim unbound, I liked the random options and the ability to random spawn in a requiem friendly place. Also you only have to set everything up once before character creation in the mcm which is priceless for any modlist other than yours... Love the automation of that. But it is helpful for me cause I do my own changes and add a few mods. Also the disable immersive divine blessings seems to just stop the punishments for crime not the blessings themselves or changes them. Not sure how that is supposed to work but I have it checked and killed someone to test it. I may just need to test it more. Or I don't actually know enough about it to know what is what. Part of why I don't like it. So many different rules for each deity it breaks immersion when I have to go look it up and makes it too tedious to use even if I get benefits. Either way I am extremely grateful this is an option.

**Comment by azraerl** [comment]
Optional -> Disable R-IDB reverts 100% of changes which R-IDB does. So Divine Blessing act like in vanilla Requiem (and deities do not like criminals)

Meanwhile non-disabled R-IDB now does not look at your crimes, apart from Zenithar (LORE). Of course Daedric stuff is still being punished.

RE: Skyrim Unbound - yeah, considering this one.

**Comment by ReikiJake** [comment]
downloaded the latest update (1.6.2) everything with the map seems to work great now.
