### ISSUE TITLE
Solution not found for broken download

### ISSUE THREAD

**Issue by H3r4mKing407** [azraerl/serenity#6]
While downloading serenity it keeps saying No solution for broken download.
![Wabbajack 9_5_2021 10_59_29 PM](https://user-images.githubusercontent.com/90168576/132159010-0943de1f-82e4-4408-9b25-c43f21431f6d.png)

**Comment by azraerl** [comment]
While this is annoying, this is somewhat normal. Network errors might lead to such errors.

Below steps, in order, are known to help immensely with such:
- Wait until Wabbajack finishes with error state, saying `broken download`, and restart install process. Wabbajack will re-try failed files (and re-use everything what was properly downloaded);
- Use `network workaround` in WJ options, if broken file resides on WJ CDN / LL / MEGA;
- For Nexus downloads: change download server in your Nexus settings (only for premium users);
- Download files manually (possible for anything apart of WJ CDN files).

Also I would advise you to join [Wabbajack](https://discord.gg/wabbajack) and/or [Emporio's Emporium](https://discord.gg/867QtkVuUa) - dedicated to Serenity - discord servers.

**Comment by azraerl** [comment]
Closing the issue, as this is not an essential issue with the mod list. Use discord servers mentioned for troubleshooting files download / Wabbajack install process.
