### ISSUE TITLE
How did I feel to play serenity

### ISSUE THREAD

**Issue by SavageraMaxima** [azraerl/serenity#7]
First I must make it clear that English is not my main language.
As a Skyrim player for many years, playing serenity as an orc and as a soldier in an orc camp, I first felt that the weight of the armor made it impossible for me to run, so I had to remove it, which I had to put back on when I found my first enemy ( A pack of wolves) in which I died in seconds, I thought it was weird, but anyway, I followed the game and had my second fight against a simple crab, and I actually felt like an idiot and not an orc, because I could barely deal damage and received a lot from him.
So I tried to play again but this time vanilla, and I died in the first match with just one hit.

**Additional context**
Conclusion:
The modpack has a very nice look, the quality is impeccable, but unfortunately I didn't have fun because I didn't feel the strength in my character, he looked so weak that unfortunately it couldn't be an orc, I think this detail of the weight of the armor should be corrected ( having to withdraw to run and put back into battle is bad) and the strength of the character must be corrected, very weak, the rest of the game unfortunately I couldn't see because I lost my lust after dying to the first enemy in vanilla, good luck with the fixes .

**Comment by azraerl** [comment]
First of all, you should find this useful (use google translator): [Guide - How to adapt my gameplay for Requiem ?](https://www.reddit.com/r/skyrimrequiem/comments/fdsz4y/guide_how_to_adapt_my_gameplay_for_requiem/)

Also here you can find answers about almost everything: [Guides, resources & links for beginners and advanced players](https://www.reddit.com/r/skyrimrequiem/comments/hijmml/guides_resources_links_for_beginners_and_advanced/)

**Comment by azraerl** [comment]
No further expedition, closed.
