### ISSUE TITLE
cant turn propally while attacking (its extrem slow) not sure if this is a bug (is also possible to change that?)

### ISSUE THREAD

**Issue by SHIIIZA117** [azraerl/serenity#9]
Describe the bug
When i am attacking i cant look left and right

To Reproduce
nothing speacial, just attack and turn around at the same time

Go to '...'
Do '...'
Expected behavior
the camera should move fast and smooth like in vanilla

Modlist version
latest.

Did you add any additional mods?

No

**Comment by azraerl** [comment]
As above:
Not a bug, but intended feature - realistic attack commitment, which is provided by Mortal Enemies Synthesis patch.
